# Generated by Django 3.1.3 on 2021-03-14 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', tinymce.models.HTMLField()),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('idea_submission_deadline', models.DateField()),
                ('thumbnail', models.ImageField(blank=True, default='defaultbg.jpg', upload_to='')),
                ('subscribers_count', models.IntegerField(default=0)),
                ('state', models.CharField(choices=[('ACTIVE', 'Active'), ('ENDED', 'Ended')], default='ACTIVE', max_length=6)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('criterias', models.ManyToManyField(to='challenges.Criteria')),
                ('subscribers', models.ManyToManyField(blank=True, default=None, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
